### ISSUE TITLE
Testimonial processing

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#226] opened 2019-01-15 20:56 UTC
### Description

Make a thing so we can manage testimonials. All are on the school

Web to lead form comes in with testimonial, automatically creates testimonial record.
Testimonial record will link to person. See the testimonial that exists on school and one being submitted and then buttons to approve or reject.

**Comment by meeragovindaraju** [comment] 2019-01-15 21:01
Trello card: https://trello.com/c/PMYAELcf/552-testimonial-processing

**Comment by allisonhowell** [comment] 2019-03-04 18:43
Duplicate of a SF trello card.

**Closed by allisonhowell** 2019-03-04 18:43 UTC
